package country

import (
	"regexp"
)

var names = map[string]string{
	"AX":  "248",
	"ALA": "248",
	"AL":  "008",
	"ALB": "008",
	"DZ":  "012",
	"DZA": "012",
	"AS":  "016",
	"ASM": "016",
	"AD":  "020",
	"AND": "020",
	"AO":  "024",
	"AGO": "024",
	"AI":  "660",
	"AIA": "660",
	"AQ":  "010",
	"ATA": "010",
	"AG":  "028",
	"ATG": "028",
	"AR":  "032",
	"ARG": "032",
	"AM":  "051",
	"ARM": "051",
	"AW":  "533",
	"ABW": "533",
	"AU":  "036",
	"AUS": "036",
	"AT":  "040",
	"AUT": "040",
	"AZ":  "031",
	"AZE": "031",
	"BS":  "044",
	"BHS": "044",
	"BH":  "048",
	"BHR": "048",
	"BD":  "050",
	"BGD": "050",
	"BB":  "052",
	"BRB": "052",
	"BY":  "112",
	"BLR": "112",
	"BE":  "056",
	"BEL": "056",
	"BZ":  "084",
	"BLZ": "084",
	"BJ":  "204",
	"BEN": "204",
	"BM":  "060",
	"BMU": "060",
	"BT":  "064",
	"BTN": "064",
	"BO":  "068",
	"BOL": "068",
	"BA":  "070",
	"BIH": "070",
	"BW":  "072",
	"BWA": "072",
	"BV":  "074",
	"BVT": "074",
	"BR":  "076",
	"BRA": "076",
	"IO":  "086",
	"IOT": "086",
	"BN":  "096",
	"BRN": "096",
	"BG":  "100",
	"BGR": "100",
	"BF":  "854",
	"BFA": "854",
	"BI":  "108",
	"BDI": "108",
	"KH":  "116",
	"KHM": "116",
	"CM":  "120",
	"CMR": "120",
	"CA":  "124",
	"CAN": "124",
	"CV":  "132",
	"CPV": "132",
	"KY":  "136",
	"CYM": "136",
	"CF":  "140",
	"CAF": "140",
	"TD":  "148",
	"TCD": "148",
	"CL":  "152",
	"CHL": "152",
	"CN":  "156",
	"CHN": "156",
	"CX":  "162",
	"CXR": "162",
	"CC":  "166",
	"CCK": "166",
	"CO":  "170",
	"COL": "170",
	"KM":  "174",
	"COM": "174",
	"CG":  "178",
	"COG": "178",
	"CD":  "180",
	"COD": "180",
	"CK":  "184",
	"COK": "184",
	"CR":  "188",
	"CRI": "188",
	"CI":  "384",
	"CIV": "384",
	"HR":  "191",
	"HRV": "191",
	"CU":  "192",
	"CUB": "192",
	"CY":  "196",
	"CYP": "196",
	"CZ":  "203",
	"CZE": "203",
	"DK":  "208",
	"DNK": "208",
	"DJ":  "262",
	"DJI": "262",
	"DM":  "212",
	"DMA": "212",
	"DO":  "214",
	"DOM": "214",
	"EC":  "218",
	"ECU": "218",
	"EG":  "818",
	"EGY": "818",
	"SV":  "222",
	"SLV": "222",
	"GQ":  "226",
	"GNQ": "226",
	"ER":  "232",
	"ERI": "232",
	"EE":  "233",
	"EST": "233",
	"ET":  "231",
	"ETH": "231",
	"FK":  "238",
	"FLK": "238",
	"FO":  "234",
	"FRO": "234",
	"FJ":  "242",
	"FJI": "242",
	"FI":  "246",
	"FIN": "246",
	"FR":  "250",
	"FRA": "250",
	"GF":  "254",
	"GUF": "254",
	"PF":  "258",
	"PYF": "258",
	"TF":  "260",
	"ATF": "260",
	"GA":  "266",
	"GAB": "266",
	"GM":  "270",
	"GMB": "270",
	"GE":  "268",
	"GEO": "268",
	"DE":  "276",
	"DEU": "276",
	"GH":  "288",
	"GHA": "288",
	"GI":  "292",
	"GIB": "292",
	"GR":  "300",
	"GRC": "300",
	"GL":  "304",
	"GRL": "304",
	"GD":  "308",
	"GRD": "308",
	"GP":  "312",
	"GLP": "312",
	"GU":  "316",
	"GUM": "316",
	"GT":  "320",
	"GTM": "320",
	"GG":  "831",
	"GGY": "831",
	"GN":  "324",
	"GIN": "324",
	"GW":  "624",
	"GNB": "624",
	"GY":  "328",
	"GUY": "328",
	"HT":  "332",
	"HTI": "332",
	"HM":  "334",
	"HMD": "334",
	"HN":  "340",
	"HND": "340",
	"HK":  "344",
	"HKG": "344",
	"HU":  "348",
	"HUN": "348",
	"IS":  "352",
	"ISL": "352",
	"IN":  "356",
	"IND": "356",
	"ID":  "360",
	"IDN": "360",
	"IR":  "364",
	"IRN": "364",
	"IQ":  "368",
	"IRQ": "368",
	"IE":  "372",
	"IRL": "372",
	"IM":  "833",
	"IMN": "833",
	"IL":  "376",
	"ISR": "376",
	"IT":  "380",
	"ITA": "380",
	"JM":  "388",
	"JAM": "388",
	"JP":  "392",
	"JPN": "392",
	"JE":  "832",
	"JEY": "832",
	"JO":  "400",
	"JOR": "400",
	"KZ":  "398",
	"KAZ": "398",
	"KE":  "404",
	"KEN": "404",
	"KI":  "296",
	"KIR": "296",
	"KP":  "408",
	"PRK": "408",
	"KR":  "410",
	"KOR": "410",
	"KW":  "414",
	"KWT": "414",
	"KG":  "417",
	"KGZ": "417",
	"LA":  "418",
	"LAO": "418",
	"LV":  "428",
	"LVA": "428",
	"LB":  "422",
	"LBN": "422",
	"LS":  "426",
	"LSO": "426",
	"LR":  "430",
	"LBR": "430",
	"LY":  "434",
	"LBY": "434",
	"LI":  "438",
	"LIE": "438",
	"LT":  "440",
	"LTU": "440",
	"LU":  "442",
	"LUX": "442",
	"MO":  "446",
	"MAC": "446",
	"MK":  "807",
	"MKD": "807",
	"MG":  "450",
	"MDG": "450",
	"MW":  "454",
	"MWI": "454",
	"MY":  "458",
	"MYS": "458",
	"MV":  "462",
	"MDV": "462",
	"ML":  "466",
	"MLI": "466",
	"MT":  "470",
	"MLT": "470",
	"MH":  "584",
	"MHL": "584",
	"MQ":  "474",
	"MTQ": "474",
	"MR":  "478",
	"MRT": "478",
	"MU":  "480",
	"MUS": "480",
	"YT":  "175",
	"MYT": "175",
	"MX":  "484",
	"MEX": "484",
	"FM":  "583",
	"FSM": "583",
	"MD":  "498",
	"MDA": "498",
	"MC":  "492",
	"MCO": "492",
	"MN":  "496",
	"MNG": "496",
	"ME":  "499",
	"MNE": "499",
	"MS":  "500",
	"MSR": "500",
	"MA":  "504",
	"MAR": "504",
	"MZ":  "508",
	"MOZ": "508",
	"MM":  "104",
	"MMR": "104",
	"NA":  "516",
	"NAM": "516",
	"NR":  "520",
	"NRU": "520",
	"NP":  "524",
	"NPL": "524",
	"NL":  "528",
	"NLD": "528",
	"AN":  "530",
	"ANT": "530",
	"NC":  "540",
	"NCL": "540",
	"NZ":  "554",
	"NZL": "554",
	"NI":  "558",
	"NIC": "558",
	"NE":  "562",
	"NER": "562",
	"NG":  "566",
	"NGA": "566",
	"NU":  "570",
	"NIU": "570",
	"NF":  "574",
	"NFK": "574",
	"MP":  "580",
	"MNP": "580",
	"NO":  "578",
	"NOR": "578",
	"OM":  "512",
	"OMN": "512",
	"PK":  "586",
	"PAK": "586",
	"PW":  "585",
	"PLW": "585",
	"PS":  "275",
	"PSE": "275",
	"PA":  "591",
	"PAN": "591",
	"PG":  "598",
	"PNG": "598",
	"PY":  "600",
	"PRY": "600",
	"PE":  "604",
	"PER": "604",
	"PH":  "608",
	"PHL": "608",
	"PN":  "612",
	"PCN": "612",
	"PL":  "616",
	"POL": "616",
	"PT":  "620",
	"PRT": "620",
	"PR":  "630",
	"PRI": "630",
	"QA":  "634",
	"QAT": "634",
	"RE":  "638",
	"REU": "638",
	"RO":  "642",
	"ROU": "642",
	"RU":  "643",
	"RUS": "643",
	"RW":  "646",
	"RWA": "646",
	"BL":  "652",
	"BLM": "652",
	"SH":  "654",
	"SHN": "654",
	"KN":  "659",
	"KNA": "659",
	"LC":  "662",
	"LCA": "662",
	"MF":  "663",
	"MAF": "663",
	"PM":  "666",
	"SPM": "666",
	"VC":  "670",
	"VCT": "670",
	"WS":  "882",
	"WSM": "882",
	"SM":  "674",
	"SMR": "674",
	"ST":  "678",
	"STP": "678",
	"SA":  "682",
	"SAU": "682",
	"SN":  "686",
	"SEN": "686",
	"RS":  "688",
	"SRB": "688",
	"SC":  "690",
	"SYC": "690",
	"SL":  "694",
	"SLE": "694",
	"SG":  "702",
	"SGP": "702",
	"SK":  "703",
	"SVK": "703",
	"SI":  "705",
	"SVN": "705",
	"SB":  "090",
	"SLB": "090",
	"SO":  "706",
	"SOM": "706",
	"ZA":  "710",
	"ZAF": "710",
	"GS":  "239",
	"SGS": "239",
	"SS":  "728",
	"SSD": "728",
	"ES":  "724",
	"ESP": "724",
	"LK":  "144",
	"LKA": "144",
	"SD":  "736",
	"SDN": "736",
	"SR":  "740",
	"SUR": "740",
	"SJ":  "744",
	"SJM": "744",
	"SZ":  "748",
	"SWZ": "748",
	"SE":  "752",
	"SWE": "752",
	"CH":  "756",
	"CHE": "756",
	"SY":  "760",
	"SYR": "760",
	"TW":  "158",
	"TWN": "158",
	"TJ":  "762",
	"TJK": "762",
	"TZ":  "834",
	"TZA": "834",
	"TH":  "764",
	"THA": "764",
	"TL":  "626",
	"TLS": "626",
	"TG":  "768",
	"TGO": "768",
	"TK":  "772",
	"TKL": "772",
	"TO":  "776",
	"TON": "776",
	"TT":  "780",
	"TTO": "780",
	"TN":  "788",
	"TUN": "788",
	"TR":  "792",
	"TUR": "792",
	"TM":  "795",
	"TKM": "795",
	"TC":  "796",
	"TCA": "796",
	"TV":  "798",
	"TUV": "798",
	"UG":  "800",
	"UGA": "800",
	"UA":  "804",
	"UKR": "804",
	"AE":  "784",
	"ARE": "784",
	"GB":  "826",
	"GBR": "826",
	"US":  "840",
	"USA": "840",
	"UM":  "581",
	"UMI": "581",
	"UY":  "858",
	"URY": "858",
	"UZ":  "860",
	"UZB": "860",
	"VU":  "548",
	"VUT": "548",
	"VA":  "336",
	"VAT": "336",
	"VE":  "862",
	"VEN": "862",
	"VN":  "704",
	"VNM": "704",
	"VG":  "092",
	"VGB": "092",
	"ZM":  "894",
	"ZMB": "894",
	"ZW":  "716",
	"ZWE": "716",
	"YE":  "887",
	"YEM": "887",
	"XK":  "998",
	"UNK": "998",
	"CW":  "531",
	"CUW": "531",
	"WF":  "876",
	"WLF": "876",
	"VI":  "850",
	"VIR": "850",
	"BQ":  "535",
	"BES": "535",
	"SX":  "534",
	"SXM": "534",
	"UN":  "000",
	"UNN": "000",
}

var codes = map[string]map[string]string{
	"004": {"code": "004", "alpha2": "AF", "alpha3": "AFG", "continent": "1"},
	"248": {"code": "248", "alpha2": "AX", "alpha3": "ALA", "continent": "2"},
	"008": {"code": "008", "alpha2": "AL", "alpha3": "ALB", "continent": "2"},
	"012": {"code": "012", "alpha2": "DZ", "alpha3": "DZA", "continent": "3"},
	"016": {"code": "016", "alpha2": "AS", "alpha3": "ASM", "continent": "4"},
	"020": {"code": "020", "alpha2": "AD", "alpha3": "AND", "continent": "2"},
	"024": {"code": "024", "alpha2": "AO", "alpha3": "AGO", "continent": "3"},
	"660": {"code": "660", "alpha2": "AI", "alpha3": "AIA", "continent": "6"},
	"010": {"code": "010", "alpha2": "AQ", "alpha3": "ATA", "continent": "7"},
	"028": {"code": "028", "alpha2": "AG", "alpha3": "ATG", "continent": "6"},
	"032": {"code": "032", "alpha2": "AR", "alpha3": "ARG", "continent": "6"},
	"051": {"code": "051", "alpha2": "AM", "alpha3": "ARM", "continent": "2"},
	"533": {"code": "533", "alpha2": "AW", "alpha3": "ABW", "continent": "6"},
	"036": {"code": "036", "alpha2": "AU", "alpha3": "AUS", "continent": "4"},
	"040": {"code": "040", "alpha2": "AT", "alpha3": "AUT", "continent": "2"},
	"031": {"code": "031", "alpha2": "AZ", "alpha3": "AZE", "continent": "2"},
	"044": {"code": "044", "alpha2": "BS", "alpha3": "BHS", "continent": "6"},
	"048": {"code": "048", "alpha2": "BH", "alpha3": "BHR", "continent": "1"},
	"050": {"code": "050", "alpha2": "BD", "alpha3": "BGD", "continent": "1"},
	"052": {"code": "052", "alpha2": "BB", "alpha3": "BRB", "continent": "6"},
	"112": {"code": "112", "alpha2": "BY", "alpha3": "BLR", "continent": "2"},
	"056": {"code": "056", "alpha2": "BE", "alpha3": "BEL", "continent": "2"},
	"084": {"code": "084", "alpha2": "BZ", "alpha3": "BLZ", "continent": "6"},
	"204": {"code": "204", "alpha2": "BJ", "alpha3": "BEN", "continent": "3"},
	"060": {"code": "060", "alpha2": "BM", "alpha3": "BMU", "continent": "5"},
	"064": {"code": "064", "alpha2": "BT", "alpha3": "BTN", "continent": "1"},
	"068": {"code": "068", "alpha2": "BO", "alpha3": "BOL", "continent": "6"},
	"070": {"code": "070", "alpha2": "BA", "alpha3": "BIH", "continent": "2"},
	"072": {"code": "072", "alpha2": "BW", "alpha3": "BWA", "continent": "3"},
	"074": {"code": "074", "alpha2": "BV", "alpha3": "BVT", "continent": "7"},
	"076": {"code": "076", "alpha2": "BR", "alpha3": "BRA", "continent": "6"},
	"086": {"code": "086", "alpha2": "IO", "alpha3": "IOT", "continent": "1"},
	"096": {"code": "096", "alpha2": "BN", "alpha3": "BRN", "continent": "1"},
	"100": {"code": "100", "alpha2": "BG", "alpha3": "BGR", "continent": "2"},
	"854": {"code": "854", "alpha2": "BF", "alpha3": "BFA", "continent": "3"},
	"108": {"code": "108", "alpha2": "BI", "alpha3": "BDI", "continent": "3"},
	"116": {"code": "116", "alpha2": "KH", "alpha3": "KHM", "continent": "1"},
	"120": {"code": "120", "alpha2": "CM", "alpha3": "CMR", "continent": "3"},
	"124": {"code": "124", "alpha2": "CA", "alpha3": "CAN", "continent": "5"},
	"132": {"code": "132", "alpha2": "CV", "alpha3": "CPV", "continent": "3"},
	"136": {"code": "136", "alpha2": "KY", "alpha3": "CYM", "continent": "6"},
	"140": {"code": "140", "alpha2": "CF", "alpha3": "CAF", "continent": "3"},
	"148": {"code": "148", "alpha2": "TD", "alpha3": "TCD", "continent": "3"},
	"152": {"code": "152", "alpha2": "CL", "alpha3": "CHL", "continent": "6"},
	"156": {"code": "156", "alpha2": "CN", "alpha3": "CHN", "continent": "1"},
	"162": {"code": "162", "alpha2": "CX", "alpha3": "CXR", "continent": "4"},
	"166": {"code": "166", "alpha2": "CC", "alpha3": "CCK", "continent": "4"},
	"170": {"code": "170", "alpha2": "CO", "alpha3": "COL", "continent": "6"},
	"174": {"code": "174", "alpha2": "KM", "alpha3": "COM", "continent": "3"},
	"178": {"code": "178", "alpha2": "CG", "alpha3": "COG", "continent": "3"},
	"180": {"code": "180", "alpha2": "CD", "alpha3": "COD", "continent": "3"},
	"184": {"code": "184", "alpha2": "CK", "alpha3": "COK", "continent": "4"},
	"188": {"code": "188", "alpha2": "CR", "alpha3": "CRI", "continent": "6"},
	"384": {"code": "384", "alpha2": "CI", "alpha3": "CIV", "continent": "3"},
	"191": {"code": "191", "alpha2": "HR", "alpha3": "HRV", "continent": "2"},
	"192": {"code": "192", "alpha2": "CU", "alpha3": "CUB", "continent": "6"},
	"196": {"code": "196", "alpha2": "CY", "alpha3": "CYP", "continent": "1"},
	"203": {"code": "203", "alpha2": "CZ", "alpha3": "CZE", "continent": "2"},
	"208": {"code": "208", "alpha2": "DK", "alpha3": "DNK", "continent": "2"},
	"262": {"code": "262", "alpha2": "DJ", "alpha3": "DJI", "continent": "3"},
	"212": {"code": "212", "alpha2": "DM", "alpha3": "DMA", "continent": "6"},
	"214": {"code": "214", "alpha2": "DO", "alpha3": "DOM", "continent": "6"},
	"218": {"code": "218", "alpha2": "EC", "alpha3": "ECU", "continent": "6"},
	"818": {"code": "818", "alpha2": "EG", "alpha3": "EGY", "continent": "3"},
	"222": {"code": "222", "alpha2": "SV", "alpha3": "SLV", "continent": "6"},
	"226": {"code": "226", "alpha2": "GQ", "alpha3": "GNQ", "continent": "3"},
	"232": {"code": "232", "alpha2": "ER", "alpha3": "ERI", "continent": "3"},
	"233": {"code": "233", "alpha2": "EE", "alpha3": "EST", "continent": "2"},
	"231": {"code": "231", "alpha2": "ET", "alpha3": "ETH", "continent": "3"},
	"238": {"code": "238", "alpha2": "FK", "alpha3": "FLK", "continent": "6"},
	"234": {"code": "234", "alpha2": "FO", "alpha3": "FRO", "continent": "2"},
	"242": {"code": "242", "alpha2": "FJ", "alpha3": "FJI", "continent": "4"},
	"246": {"code": "246", "alpha2": "FI", "alpha3": "FIN", "continent": "2"},
	"250": {"code": "250", "alpha2": "FR", "alpha3": "FRA", "continent": "2"},
	"254": {"code": "254", "alpha2": "GF", "alpha3": "GUF", "continent": "6"},
	"258": {"code": "258", "alpha2": "PF", "alpha3": "PYF", "continent": "4"},
	"260": {"code": "260", "alpha2": "TF", "alpha3": "ATF", "continent": "3"},
	"266": {"code": "266", "alpha2": "GA", "alpha3": "GAB", "continent": "3"},
	"270": {"code": "270", "alpha2": "GM", "alpha3": "GMB", "continent": "3"},
	"268": {"code": "268", "alpha2": "GE", "alpha3": "GEO", "continent": "2"},
	"276": {"code": "276", "alpha2": "DE", "alpha3": "DEU", "continent": "2"},
	"288": {"code": "288", "alpha2": "GH", "alpha3": "GHA", "continent": "3"},
	"292": {"code": "292", "alpha2": "GI", "alpha3": "GIB", "continent": "2"},
	"300": {"code": "300", "alpha2": "GR", "alpha3": "GRC", "continent": "2"},
	"304": {"code": "304", "alpha2": "GL", "alpha3": "GRL", "continent": "5"},
	"308": {"code": "308", "alpha2": "GD", "alpha3": "GRD", "continent": "6"},
	"312": {"code": "312", "alpha2": "GP", "alpha3": "GLP", "continent": "6"},
	"316": {"code": "316", "alpha2": "GU", "alpha3": "GUM", "continent": "1"},
	"320": {"code": "320", "alpha2": "GT", "alpha3": "GTM", "continent": "6"},
	"831": {"code": "831", "alpha2": "GG", "alpha3": "GGY", "continent": "2"},
	"324": {"code": "324", "alpha2": "GN", "alpha3": "GIN", "continent": "3"},
	"624": {"code": "624", "alpha2": "GW", "alpha3": "GNB", "continent": "3"},
	"328": {"code": "328", "alpha2": "GY", "alpha3": "GUY", "continent": "6"},
	"332": {"code": "332", "alpha2": "HT", "alpha3": "HTI", "continent": "6"},
	"334": {"code": "334", "alpha2": "HM", "alpha3": "HMD", "continent": "4"},
	"340": {"code": "340", "alpha2": "HN", "alpha3": "HND", "continent": "6"},
	"344": {"code": "344", "alpha2": "HK", "alpha3": "HKG", "continent": "1"},
	"348": {"code": "348", "alpha2": "HU", "alpha3": "HUN", "continent": "2"},
	"352": {"code": "352", "alpha2": "IS", "alpha3": "ISL", "continent": "2"},
	"356": {"code": "356", "alpha2": "IN", "alpha3": "IND", "continent": "1"},
	"360": {"code": "360", "alpha2": "ID", "alpha3": "IDN", "continent": "1"},
	"364": {"code": "364", "alpha2": "IR", "alpha3": "IRN", "continent": "1"},
	"368": {"code": "368", "alpha2": "IQ", "alpha3": "IRQ", "continent": "1"},
	"372": {"code": "372", "alpha2": "IE", "alpha3": "IRL", "continent": "2"},
	"833": {"code": "833", "alpha2": "IM", "alpha3": "IMN", "continent": "2"},
	"376": {"code": "376", "alpha2": "IL", "alpha3": "ISR", "continent": "1"},
	"380": {"code": "380", "alpha2": "IT", "alpha3": "ITA", "continent": "2"},
	"388": {"code": "388", "alpha2": "JM", "alpha3": "JAM", "continent": "6"},
	"392": {"code": "392", "alpha2": "JP", "alpha3": "JPN", "continent": "1"},
	"832": {"code": "832", "alpha2": "JE", "alpha3": "JEY", "continent": "2"},
	"400": {"code": "400", "alpha2": "JO", "alpha3": "JOR", "continent": "1"},
	"398": {"code": "398", "alpha2": "KZ", "alpha3": "KAZ", "continent": "1"},
	"404": {"code": "404", "alpha2": "KE", "alpha3": "KEN", "continent": "3"},
	"296": {"code": "296", "alpha2": "KI", "alpha3": "KIR", "continent": "4"},
	"408": {"code": "408", "alpha2": "KP", "alpha3": "PRK", "continent": "1"},
	"410": {"code": "410", "alpha2": "KR", "alpha3": "KOR", "continent": "1"},
	"414": {"code": "414", "alpha2": "KW", "alpha3": "KWT", "continent": "1"},
	"417": {"code": "417", "alpha2": "KG", "alpha3": "KGZ", "continent": "1"},
	"418": {"code": "418", "alpha2": "LA", "alpha3": "LAO", "continent": "1"},
	"428": {"code": "428", "alpha2": "LV", "alpha3": "LVA", "continent": "2"},
	"422": {"code": "422", "alpha2": "LB", "alpha3": "LBN", "continent": "1"},
	"426": {"code": "426", "alpha2": "LS", "alpha3": "LSO", "continent": "3"},
	"430": {"code": "430", "alpha2": "LR", "alpha3": "LBR", "continent": "3"},
	"434": {"code": "434", "alpha2": "LY", "alpha3": "LBY", "continent": "3"},
	"438": {"code": "438", "alpha2": "LI", "alpha3": "LIE", "continent": "2"},
	"440": {"code": "440", "alpha2": "LT", "alpha3": "LTU", "continent": "2"},
	"442": {"code": "442", "alpha2": "LU", "alpha3": "LUX", "continent": "2"},
	"446": {"code": "446", "alpha2": "MO", "alpha3": "MAC", "continent": "1"},
	"807": {"code": "807", "alpha2": "MK", "alpha3": "MKD", "continent": "2"},
	"450": {"code": "450", "alpha2": "MG", "alpha3": "MDG", "continent": "3"},
	"454": {"code": "454", "alpha2": "MW", "alpha3": "MWI", "continent": "3"},
	"458": {"code": "458", "alpha2": "MY", "alpha3": "MYS", "continent": "1"},
	"462": {"code": "462", "alpha2": "MV", "alpha3": "MDV", "continent": "1"},
	"466": {"code": "466", "alpha2": "ML", "alpha3": "MLI", "continent": "3"},
	"470": {"code": "470", "alpha2": "MT", "alpha3": "MLT", "continent": "2"},
	"584": {"code": "584", "alpha2": "MH", "alpha3": "MHL", "continent": "4"},
	"474": {"code": "474", "alpha2": "MQ", "alpha3": "MTQ", "continent": "6"},
	"478": {"code": "478", "alpha2": "MR", "alpha3": "MRT", "continent": "3"},
	"480": {"code": "480", "alpha2": "MU", "alpha3": "MUS", "continent": "3"},
	"175": {"code": "175", "alpha2": "YT", "alpha3": "MYT", "continent": "3"},
	"484": {"code": "484", "alpha2": "MX", "alpha3": "MEX", "continent": "6"},
	"583": {"code": "583", "alpha2": "FM", "alpha3": "FSM", "continent": "4"},
	"498": {"code": "498", "alpha2": "MD", "alpha3": "MDA", "continent": "2"},
	"492": {"code": "492", "alpha2": "MC", "alpha3": "MCO", "continent": "2"},
	"496": {"code": "496", "alpha2": "MN", "alpha3": "MNG", "continent": "1"},
	"499": {"code": "499", "alpha2": "ME", "alpha3": "MNE", "continent": "2"},
	"500": {"code": "500", "alpha2": "MS", "alpha3": "MSR", "continent": "6"},
	"504": {"code": "504", "alpha2": "MA", "alpha3": "MAR", "continent": "3"},
	"508": {"code": "508", "alpha2": "MZ", "alpha3": "MOZ", "continent": "3"},
	"104": {"code": "104", "alpha2": "MM", "alpha3": "MMR", "continent": "1"},
	"516": {"code": "516", "alpha2": "NA", "alpha3": "NAM", "continent": "3"},
	"520": {"code": "520", "alpha2": "NR", "alpha3": "NRU", "continent": "4"},
	"524": {"code": "524", "alpha2": "NP", "alpha3": "NPL", "continent": "1"},
	"528": {"code": "528", "alpha2": "NL", "alpha3": "NLD", "continent": "2"},
	"530": {"code": "530", "alpha2": "AN", "alpha3": "ANT", "continent": "6"},
	"540": {"code": "540", "alpha2": "NC", "alpha3": "NCL", "continent": "4"},
	"554": {"code": "554", "alpha2": "NZ", "alpha3": "NZL", "continent": "4"},
	"558": {"code": "558", "alpha2": "NI", "alpha3": "NIC", "continent": "6"},
	"562": {"code": "562", "alpha2": "NE", "alpha3": "NER", "continent": "3"},
	"566": {"code": "566", "alpha2": "NG", "alpha3": "NGA", "continent": "3"},
	"570": {"code": "570", "alpha2": "NU", "alpha3": "NIU", "continent": "4"},
	"574": {"code": "574", "alpha2": "NF", "alpha3": "NFK", "continent": "4"},
	"580": {"code": "580", "alpha2": "MP", "alpha3": "MNP", "continent": "1"},
	"578": {"code": "578", "alpha2": "NO", "alpha3": "NOR", "continent": "2"},
	"512": {"code": "512", "alpha2": "OM", "alpha3": "OMN", "continent": "1"},
	"586": {"code": "586", "alpha2": "PK", "alpha3": "PAK", "continent": "1"},
	"585": {"code": "585", "alpha2": "PW", "alpha3": "PLW", "continent": "4"},
	"275": {"code": "275", "alpha2": "PS", "alpha3": "PSE", "continent": "1"},
	"591": {"code": "591", "alpha2": "PA", "alpha3": "PAN", "continent": "6"},
	"598": {"code": "598", "alpha2": "PG", "alpha3": "PNG", "continent": "4"},
	"600": {"code": "600", "alpha2": "PY", "alpha3": "PRY", "continent": "6"},
	"604": {"code": "604", "alpha2": "PE", "alpha3": "PER", "continent": "6"},
	"608": {"code": "608", "alpha2": "PH", "alpha3": "PHL", "continent": "1"},
	"612": {"code": "612", "alpha2": "PN", "alpha3": "PCN", "continent": "4"},
	"616": {"code": "616", "alpha2": "PL", "alpha3": "POL", "continent": "2"},
	"620": {"code": "620", "alpha2": "PT", "alpha3": "PRT", "continent": "2"},
	"630": {"code": "630", "alpha2": "PR", "alpha3": "PRI", "continent": "6"},
	"634": {"code": "634", "alpha2": "QA", "alpha3": "QAT", "continent": "1"},
	"638": {"code": "638", "alpha2": "RE", "alpha3": "REU", "continent": "3"},
	"642": {"code": "642", "alpha2": "RO", "alpha3": "ROU", "continent": "2"},
	"643": {"code": "643", "alpha2": "RU", "alpha3": "RUS", "continent": "2"},
	"646": {"code": "646", "alpha2": "RW", "alpha3": "RWA", "continent": "3"},
	"652": {"code": "652", "alpha2": "BL", "alpha3": "BLM", "continent": "6"},
	"654": {"code": "654", "alpha2": "SH", "alpha3": "SHN", "continent": "6"},
	"659": {"code": "659", "alpha2": "KN", "alpha3": "KNA", "continent": "6"},
	"662": {"code": "662", "alpha2": "LC", "alpha3": "LCA", "continent": "6"},
	"663": {"code": "663", "alpha2": "MF", "alpha3": "MAF", "continent": "6"},
	"666": {"code": "666", "alpha2": "PM", "alpha3": "SPM", "continent": "6"},
	"670": {"code": "670", "alpha2": "VC", "alpha3": "VCT", "continent": "6"},
	"882": {"code": "882", "alpha2": "WS", "alpha3": "WSM", "continent": "4"},
	"674": {"code": "674", "alpha2": "SM", "alpha3": "SMR", "continent": "2"},
	"678": {"code": "678", "alpha2": "ST", "alpha3": "STP", "continent": "3"},
	"682": {"code": "682", "alpha2": "SA", "alpha3": "SAU", "continent": "1"},
	"686": {"code": "686", "alpha2": "SN", "alpha3": "SEN", "continent": "3"},
	"688": {"code": "688", "alpha2": "RS", "alpha3": "SRB", "continent": "2"},
	"690": {"code": "690", "alpha2": "SC", "alpha3": "SYC", "continent": "3"},
	"694": {"code": "694", "alpha2": "SL", "alpha3": "SLE", "continent": "3"},
	"702": {"code": "702", "alpha2": "SG", "alpha3": "SGP", "continent": "1"},
	"703": {"code": "703", "alpha2": "SK", "alpha3": "SVK", "continent": "2"},
	"705": {"code": "705", "alpha2": "SI", "alpha3": "SVN", "continent": "2"},
	"090": {"code": "090", "alpha2": "SB", "alpha3": "SLB", "continent": "4"},
	"706": {"code": "706", "alpha2": "SO", "alpha3": "SOM", "continent": "3"},
	"710": {"code": "710", "alpha2": "ZA", "alpha3": "ZAF", "continent": "3"},
	"239": {"code": "239", "alpha2": "GS", "alpha3": "SGS", "continent": "6"},
	"728": {"code": "728", "alpha2": "SS", "alpha3": "SSD", "continent": "3"},
	"724": {"code": "724", "alpha2": "ES", "alpha3": "ESP", "continent": "2"},
	"144": {"code": "144", "alpha2": "LK", "alpha3": "LKA", "continent": "1"},
	"736": {"code": "736", "alpha2": "SD", "alpha3": "SDN", "continent": "3"},
	"740": {"code": "740", "alpha2": "SR", "alpha3": "SUR", "continent": "6"},
	"744": {"code": "744", "alpha2": "SJ", "alpha3": "SJM", "continent": "2"},
	"748": {"code": "748", "alpha2": "SZ", "alpha3": "SWZ", "continent": "3"},
	"752": {"code": "752", "alpha2": "SE", "alpha3": "SWE", "continent": "2"},
	"756": {"code": "756", "alpha2": "CH", "alpha3": "CHE", "continent": "2"},
	"760": {"code": "760", "alpha2": "SY", "alpha3": "SYR", "continent": "1"},
	"158": {"code": "158", "alpha2": "TW", "alpha3": "TWN", "continent": "1"},
	"762": {"code": "762", "alpha2": "TJ", "alpha3": "TJK", "continent": "1"},
	"834": {"code": "834", "alpha2": "TZ", "alpha3": "TZA", "continent": "3"},
	"764": {"code": "764", "alpha2": "TH", "alpha3": "THA", "continent": "1"},
	"626": {"code": "626", "alpha2": "TL", "alpha3": "TLS", "continent": "1"},
	"768": {"code": "768", "alpha2": "TG", "alpha3": "TGO", "continent": "3"},
	"772": {"code": "772", "alpha2": "TK", "alpha3": "TKL", "continent": "4"},
	"776": {"code": "776", "alpha2": "TO", "alpha3": "TON", "continent": "4"},
	"780": {"code": "780", "alpha2": "TT", "alpha3": "TTO", "continent": "6"},
	"788": {"code": "788", "alpha2": "TN", "alpha3": "TUN", "continent": "3"},
	"792": {"code": "792", "alpha2": "TR", "alpha3": "TUR", "continent": "1"},
	"795": {"code": "795", "alpha2": "TM", "alpha3": "TKM", "continent": "1"},
	"796": {"code": "796", "alpha2": "TC", "alpha3": "TCA", "continent": "6"},
	"798": {"code": "798", "alpha2": "TV", "alpha3": "TUV", "continent": "4"},
	"800": {"code": "800", "alpha2": "UG", "alpha3": "UGA", "continent": "3"},
	"804": {"code": "804", "alpha2": "UA", "alpha3": "UKR", "continent": "2"},
	"784": {"code": "784", "alpha2": "AE", "alpha3": "ARE", "continent": "1"},
	"826": {"code": "826", "alpha2": "GB", "alpha3": "GBR", "continent": "2"},
	"840": {"code": "840", "alpha2": "US", "alpha3": "USA", "continent": "5"},
	"581": {"code": "581", "alpha2": "UM", "alpha3": "UMI", "continent": "4"},
	"858": {"code": "858", "alpha2": "UY", "alpha3": "URY", "continent": "6"},
	"860": {"code": "860", "alpha2": "UZ", "alpha3": "UZB", "continent": "1"},
	"548": {"code": "548", "alpha2": "VU", "alpha3": "VUT", "continent": "4"},
	"336": {"code": "336", "alpha2": "VA", "alpha3": "VAT", "continent": "2"},
	"862": {"code": "862", "alpha2": "VE", "alpha3": "VEN", "continent": "6"},
	"704": {"code": "704", "alpha2": "VN", "alpha3": "VNM", "continent": "1"},
	"092": {"code": "092", "alpha2": "VG", "alpha3": "VGB", "continent": "6"},
	"894": {"code": "894", "alpha2": "ZM", "alpha3": "ZMB", "continent": "3"},
	"716": {"code": "716", "alpha2": "ZW", "alpha3": "ZWE", "continent": "3"},
	"887": {"code": "887", "alpha2": "YE", "alpha3": "YEM", "continent": "1"},
	"998": {"code": "998", "alpha2": "XK", "alpha3": "UNK", "continent": "3"},
	"531": {"code": "531", "alpha2": "CW", "alpha3": "CUW", "continent": "6"},
	"876": {"code": "876", "alpha2": "WF", "alpha3": "WLF", "continent": "4"},
	"850": {"code": "850", "alpha2": "VI", "alpha3": "VIR", "continent": "6"},
	"535": {"code": "535", "alpha2": "BQ", "alpha3": "BES", "continent": "6"},
	"534": {"code": "534", "alpha2": "SX", "alpha3": "SXM", "continent": "6"},
	"999": {"code": "999", "alpha2": "UN", "alpha3": "UNN", "continent": "0"},
	"000": {"code": "000", "alpha2": "UN", "alpha3": "UNN", "continent": "0"},
}

//var names = map[string]interface{}{
//	"004": map[string]string{"en": "Afghanistan", "zh_cn": "阿富汗", "zh_tw": "阿富汗"},
//	"008": map[string]string{"en": "Albania", "zh_cn": "阿尔巴尼亚", "zh_tw": "阿爾巴尼亞"},
//	"010": map[string]string{"en": "Antarctica", "zh_cn": "南极洲", "zh_tw": "南極洲"},
//	"012": map[string]string{"en": "Algeria", "zh_cn": "阿尔及利亚", "zh_tw": "阿爾及利亞"},
//	"016": map[string]string{"en": "American Samoa", "zh_cn": "美属萨摩亚", "zh_tw": "美屬薩摩亞"},
//	"020": map[string]string{"en": "Andorra", "zh_cn": "安道尔", "zh_tw": "安道爾"},
//	"024": map[string]string{"en": "Angola", "zh_cn": "安哥拉", "zh_tw": "安哥拉"},
//	"028": map[string]string{"en": "Antigua and Barbuda", "zh_cn": "安提瓜和巴布达", "zh_tw": "安地卡及巴布達"},
//	"031": map[string]string{"en": "Azerbaijan", "zh_cn": "阿塞拜疆", "zh_tw": "亞塞拜然"},
//	"032": map[string]string{"en": "Argentina", "zh_cn": "阿根廷", "zh_tw": "阿根廷"},
//	"036": map[string]string{"en": "Australia", "zh_cn": "澳大利亚", "zh_tw": "澳大利亞"},
//	"040": map[string]string{"en": "Austria", "zh_cn": "奥地利", "zh_tw": "奧地利"},
//	"044": map[string]string{"en": "Bahamas", "zh_cn": "巴哈马", "zh_tw": "巴哈馬"},
//	"048": map[string]string{"en": "Bahrain", "zh_cn": "巴林", "zh_tw": "巴林"},
//	"050": map[string]string{"en": "Bangladesh", "zh_cn": "孟加拉国", "zh_tw": "孟加拉國"},
//	"051": map[string]string{"en": "Armenia", "zh_cn": "亚美尼亚", "zh_tw": "亞美尼亞"},
//	"052": map[string]string{"en": "Barbados", "zh_cn": "巴巴多斯", "zh_tw": "巴貝多"},
//	"056": map[string]string{"en": "Belgium", "zh_cn": "比利时", "zh_tw": "比利時"},
//	"060": map[string]string{"en": "Bermuda", "zh_cn": "百慕大", "zh_tw": "百慕大"},
//	"064": map[string]string{"en": "Bhutan", "zh_cn": "不丹", "zh_tw": "不丹"},
//	"068": map[string]string{"en": "Bolivia, Plurinational State of", "zh_cn": "玻利维亚", "zh_tw": "玻利維亞"},
//	"070": map[string]string{"en": "Bosnia and Herzegovina", "zh_cn": "波斯尼亚和黑塞哥维那", "zh_tw": "波斯尼亞和黑塞哥維那"},
//	"072": map[string]string{"en": "Botswana", "zh_cn": "博茨瓦纳", "zh_tw": "波札那"},
//	"074": map[string]string{"en": "Bouvet Island", "zh_cn": "布韦岛", "zh_tw": "布韋島"},
//	"076": map[string]string{"en": "Brazil", "zh_cn": "巴西", "zh_tw": "巴西"},
//	"084": map[string]string{"en": "Belize", "zh_cn": "伯利兹", "zh_tw": "貝里斯"},
//	"086": map[string]string{"en": "British Indian Ocean Territory", "zh_cn": "英属印度洋领地", "zh_tw": "英屬印度洋領地"},
//	"090": map[string]string{"en": "Solomon Islands", "zh_cn": "所罗门群岛", "zh_tw": "索羅門群島"},
//	"092": map[string]string{"en": "Virgin Islands, British", "zh_cn": "英属维尔京群岛", "zh_tw": "英屬維爾京群島"},
//	"096": map[string]string{"en": "Brunei Darussalam", "zh_cn": "文莱", "zh_tw": "汶萊"},
//	"100": map[string]string{"en": "Bulgaria", "zh_cn": "保加利亚", "zh_tw": "保加利亞"},
//	"104": map[string]string{"en": "Myanmar", "zh_cn": "缅甸", "zh_tw": "緬甸"},
//	"108": map[string]string{"en": "Burundi", "zh_cn": "布隆迪", "zh_tw": "蒲隆地"},
//	"112": map[string]string{"en": "Belarus", "zh_cn": "白俄罗斯", "zh_tw": "白俄羅斯"},
//	"116": map[string]string{"en": "Cambodia", "zh_cn": "柬埔寨", "zh_tw": "柬埔寨"},
//	"120": map[string]string{"en": "Cameroon", "zh_cn": "喀麦隆", "zh_tw": "喀麥隆"},
//	"124": map[string]string{"en": "Canada", "zh_cn": "加拿大", "zh_tw": "加拿大"},
//	"132": map[string]string{"en": "Cabo Verde", "zh_cn": "佛得角", "zh_tw": "維德角"},
//	"136": map[string]string{"en": "Cayman Islands", "zh_cn": "开曼群岛", "zh_tw": "開曼群島"},
//	"140": map[string]string{"en": "Central African Republic", "zh_cn": "中非", "zh_tw": "中非"},
//	"144": map[string]string{"en": "Sri Lanka", "zh_cn": "斯里兰卡", "zh_tw": "斯里蘭卡"},
//	"148": map[string]string{"en": "Chad", "zh_cn": "乍得", "zh_tw": "查德"},
//	"152": map[string]string{"en": "Chile", "zh_cn": "智利", "zh_tw": "智利"},
//	"156": map[string]string{"en": "China", "zh_cn": "中华人民共和国", "zh_tw": "中華人民共和國"},
//	"158": map[string]string{"en": "Taiwan, Province of China", "zh_cn": "中国台湾省", "zh_tw": "中國臺灣省"},
//	"162": map[string]string{"en": "Christmas Island", "zh_cn": "圣诞岛", "zh_tw": "聖誕島"},
//	"166": map[string]string{"en": "Cocos (Keeling) Islands", "zh_cn": "科科斯（基林）群岛", "zh_tw": "科科斯（基林）群島"},
//	"170": map[string]string{"en": "Colombia", "zh_cn": "哥伦比亚", "zh_tw": "哥倫比亞"},
//	"174": map[string]string{"en": "Comoros", "zh_cn": "科摩罗", "zh_tw": "葛摩"},
//	"175": map[string]string{"en": "Mayotte", "zh_cn": "马约特", "zh_tw": "馬約特"},
//	"178": map[string]string{"en": "Congo", "zh_cn": "刚果（布）", "zh_tw": "剛果（布）"},
//	"180": map[string]string{"en": "Congo, the Democratic Republic of the", "zh_cn": "刚果（金）", "zh_tw": "剛果（金）"},
//	"184": map[string]string{"en": "Cook Islands", "zh_cn": "库克群岛", "zh_tw": "庫克群島"},
//	"188": map[string]string{"en": "Costa Rica", "zh_cn": "哥斯达黎加", "zh_tw": "哥斯大黎加"},
//	"191": map[string]string{"en": "Croatia", "zh_cn": "克罗地亚", "zh_tw": "克羅埃西亞"},
//	"192": map[string]string{"en": "Cuba", "zh_cn": "古巴", "zh_tw": "古巴"},
//	"196": map[string]string{"en": "Cyprus", "zh_cn": "塞浦路斯", "zh_tw": "塞普勒斯"},
//	"203": map[string]string{"en": "Czechia", "zh_cn": "捷克", "zh_tw": "捷克"},
//	"204": map[string]string{"en": "Benin", "zh_cn": "贝宁", "zh_tw": "貝南"},
//	"208": map[string]string{"en": "Denmark", "zh_cn": "丹麦", "zh_tw": "丹麥"},
//	"212": map[string]string{"en": "Dominica", "zh_cn": "多米尼克", "zh_tw": "多米尼克"},
//	"214": map[string]string{"en": "Dominican Republic", "zh_cn": "多米尼加", "zh_tw": "多明尼加"},
//	"218": map[string]string{"en": "Ecuador", "zh_cn": "厄瓜多尔", "zh_tw": "厄瓜多"},
//	"222": map[string]string{"en": "El Salvador", "zh_cn": "萨尔瓦多", "zh_tw": "薩爾瓦多"},
//	"226": map[string]string{"en": "Equatorial Guinea", "zh_cn": "赤道几内亚", "zh_tw": "赤道幾內亞"},
//	"231": map[string]string{"en": "Ethiopia", "zh_cn": "埃塞俄比亚", "zh_tw": "衣索比亞"},
//	"232": map[string]string{"en": "Eritrea", "zh_cn": "厄立特里亚", "zh_tw": "厄利垂亞"},
//	"233": map[string]string{"en": "Estonia", "zh_cn": "爱沙尼亚", "zh_tw": "愛沙尼亞"},
//	"234": map[string]string{"en": "Faroe Islands", "zh_cn": "法罗群岛", "zh_tw": "法羅群島"},
//	"238": map[string]string{"en": "Falkland Islands (Malvinas)", "zh_cn": "福克兰群岛", "zh_tw": "福克蘭群島"},
//	"239": map[string]string{"en": "South Georgia and the South Sandwich Islands", "zh_cn": "南乔治亚和南桑威奇群岛", "zh_tw": "南喬治亞和南桑威奇群島"},
//	"242": map[string]string{"en": "Fiji", "zh_cn": "斐济", "zh_tw": "斐濟"},
//	"246": map[string]string{"en": "Finland", "zh_cn": "芬兰", "zh_tw": "芬蘭"},
//	"248": map[string]string{"en": "Åland Islands", "zh_cn": "奥兰", "zh_tw": "奧蘭"},
//	"250": map[string]string{"en": "France", "zh_cn": "法国", "zh_tw": "法國"},
//	"254": map[string]string{"en": "French Guiana", "zh_cn": "法属圭亚那", "zh_tw": "法屬蓋亞那"},
//	"258": map[string]string{"en": "French Polynesia", "zh_cn": "法属波利尼西亚", "zh_tw": "法屬波利尼西亞"},
//	"260": map[string]string{"en": "French Southern Territories", "zh_cn": "法属南方和南极洲领地", "zh_tw": "法屬南方和南極洲領地"},
//	"262": map[string]string{"en": "Djibouti", "zh_cn": "吉布提", "zh_tw": "吉布提"},
//	"266": map[string]string{"en": "Gabon", "zh_cn": "加蓬", "zh_tw": "加彭"},
//	"268": map[string]string{"en": "Georgia", "zh_cn": "格鲁吉亚", "zh_tw": "喬治亞"},
//	"270": map[string]string{"en": "Gambia", "zh_cn": "冈比亚", "zh_tw": "甘比亞"},
//	"275": map[string]string{"en": "Palestine, State of", "zh_cn": "巴勒斯坦", "zh_tw": "巴勒斯坦"},
//	"276": map[string]string{"en": "Germany", "zh_cn": "德国", "zh_tw": "德國"},
//	"288": map[string]string{"en": "Ghana", "zh_cn": "加纳", "zh_tw": "迦納"},
//	"292": map[string]string{"en": "Gibraltar", "zh_cn": "直布罗陀", "zh_tw": "直布羅陀"},
//	"296": map[string]string{"en": "Kiribati", "zh_cn": "基里巴斯", "zh_tw": "吉里巴斯"},
//	"300": map[string]string{"en": "Greece", "zh_cn": "希腊", "zh_tw": "希臘"},
//	"304": map[string]string{"en": "Greenland", "zh_cn": "格陵兰", "zh_tw": "格陵蘭"},
//	"308": map[string]string{"en": "Grenada", "zh_cn": "格林纳达", "zh_tw": "格瑞那達"},
//	"312": map[string]string{"en": "Guadeloupe", "zh_cn": "瓜德罗普", "zh_tw": "瓜德羅普"},
//	"316": map[string]string{"en": "Guam", "zh_cn": "关岛", "zh_tw": "關島"},
//	"320": map[string]string{"en": "Guatemala", "zh_cn": "危地马拉", "zh_tw": "瓜地馬拉"},
//	"324": map[string]string{"en": "Guinea", "zh_cn": "几内亚", "zh_tw": "幾內亞"},
//	"328": map[string]string{"en": "Guyana", "zh_cn": "圭亚那", "zh_tw": "蓋亞那"},
//	"332": map[string]string{"en": "Haiti", "zh_cn": "海地", "zh_tw": "海地"},
//	"334": map[string]string{"en": "Heard Island and McDonald Islands", "zh_cn": "赫德岛和麦克唐纳群岛", "zh_tw": "赫德島和麥克唐納群島"},
//	"336": map[string]string{"en": "Holy See", "zh_cn": "梵蒂冈", "zh_tw": "梵蒂岡"},
//	"340": map[string]string{"en": "Honduras", "zh_cn": "洪都拉斯", "zh_tw": "宏都拉斯"},
//	"344": map[string]string{"en": "Hong Kong", "zh_cn": "香港", "zh_tw": "香港"},
//	"348": map[string]string{"en": "Hungary", "zh_cn": "匈牙利", "zh_tw": "匈牙利"},
//	"352": map[string]string{"en": "Iceland", "zh_cn": "冰岛", "zh_tw": "冰島"},
//	"356": map[string]string{"en": "India", "zh_cn": "印度", "zh_tw": "印度"},
//	"360": map[string]string{"en": "Indonesia", "zh_cn": "印尼", "zh_tw": "印尼"},
//	"364": map[string]string{"en": "Iran, Islamic Republic of", "zh_cn": "伊朗", "zh_tw": "伊朗"},
//	"368": map[string]string{"en": "Iraq", "zh_cn": "伊拉克", "zh_tw": "伊拉克"},
//	"372": map[string]string{"en": "Ireland", "zh_cn": "爱尔兰", "zh_tw": "愛爾蘭"},
//	"376": map[string]string{"en": "Israel", "zh_cn": "以色列", "zh_tw": "以色列"},
//	"380": map[string]string{"en": "Italy", "zh_cn": "意大利", "zh_tw": "義大利"},
//	"384": map[string]string{"en": "Côte d'Ivoire", "zh_cn": "科特迪瓦", "zh_tw": "象牙海岸"},
//	"388": map[string]string{"en": "Jamaica", "zh_cn": "牙买加", "zh_tw": "牙買加"},
//	"392": map[string]string{"en": "Japan", "zh_cn": "日本", "zh_tw": "日本"},
//	"398": map[string]string{"en": "Kazakhstan", "zh_cn": "哈萨克斯坦", "zh_tw": "哈薩克"},
//	"400": map[string]string{"en": "Jordan", "zh_cn": "约旦", "zh_tw": "約旦"},
//	"404": map[string]string{"en": "Kenya", "zh_cn": "肯尼亚", "zh_tw": "肯亞"},
//	"408": map[string]string{"en": "Korea, Democratic People's Republic of", "zh_cn": "朝鲜", "zh_tw": "朝鮮"},
//	"410": map[string]string{"en": "Korea, Republic of", "zh_cn": "韩国", "zh_tw": "韓國"},
//	"414": map[string]string{"en": "Kuwait", "zh_cn": "科威特", "zh_tw": "科威特"},
//	"417": map[string]string{"en": "Kyrgyzstan", "zh_cn": "吉尔吉斯斯坦", "zh_tw": "吉爾吉斯斯坦"},
//	"418": map[string]string{"en": "Lao People's Democratic Republic", "zh_cn": "老挝", "zh_tw": "寮國"},
//	"422": map[string]string{"en": "Lebanon", "zh_cn": "黎巴嫩", "zh_tw": "黎巴嫩"},
//	"426": map[string]string{"en": "Lesotho", "zh_cn": "莱索托", "zh_tw": "賴索托"},
//	"428": map[string]string{"en": "Latvia", "zh_cn": "拉脱维亚", "zh_tw": "拉脫維亞"},
//	"430": map[string]string{"en": "Liberia", "zh_cn": "利比里亚", "zh_tw": "賴比瑞亞"},
//	"434": map[string]string{"en": "Libya", "zh_cn": "利比亚", "zh_tw": "利比亞"},
//	"438": map[string]string{"en": "Liechtenstein", "zh_cn": "列支敦士登", "zh_tw": "列支敦斯登"},
//	"440": map[string]string{"en": "Lithuania", "zh_cn": "立陶宛", "zh_tw": "立陶宛"},
//	"442": map[string]string{"en": "Luxembourg", "zh_cn": "卢森堡", "zh_tw": "盧森堡"},
//	"446": map[string]string{"en": "Macao", "zh_cn": "澳门", "zh_tw": "澳門"},
//	"450": map[string]string{"en": "Madagascar", "zh_cn": "马达加斯加", "zh_tw": "馬達加斯加"},
//	"454": map[string]string{"en": "Malawi", "zh_cn": "马拉维", "zh_tw": "馬拉維"},
//	"458": map[string]string{"en": "Malaysia", "zh_cn": "马来西亚", "zh_tw": "馬來西亞"},
//	"462": map[string]string{"en": "Maldives", "zh_cn": "马尔代夫", "zh_tw": "馬爾地夫"},
//	"466": map[string]string{"en": "Mali", "zh_cn": "马里", "zh_tw": "馬裡"},
//	"470": map[string]string{"en": "Malta", "zh_cn": "马耳他", "zh_tw": "馬耳他"},
//	"474": map[string]string{"en": "Martinique", "zh_cn": "马提尼克", "zh_tw": "馬提尼克"},
//	"478": map[string]string{"en": "Mauritania", "zh_cn": "毛里塔尼亚", "zh_tw": "茅利塔尼亞"},
//	"480": map[string]string{"en": "Mauritius", "zh_cn": "毛里求斯", "zh_tw": "模里西斯"},
//	"484": map[string]string{"en": "Mexico", "zh_cn": "墨西哥", "zh_tw": "墨西哥"},
//	"492": map[string]string{"en": "Monaco", "zh_cn": "摩纳哥", "zh_tw": "摩納哥"},
//	"496": map[string]string{"en": "Mongolia", "zh_cn": "蒙古", "zh_tw": "蒙古"},
//	"498": map[string]string{"en": "Moldova, Republic of", "zh_cn": "摩尔多瓦", "zh_tw": "摩爾多瓦"},
//	"499": map[string]string{"en": "Montenegro", "zh_cn": "黑山", "zh_tw": "黑山"},
//	"500": map[string]string{"en": "Montserrat", "zh_cn": "蒙特塞拉特", "zh_tw": "蒙特塞拉特"},
//	"504": map[string]string{"en": "Morocco", "zh_cn": "摩洛哥", "zh_tw": "摩洛哥"},
//	"508": map[string]string{"en": "Mozambique", "zh_cn": "莫桑比克", "zh_tw": "莫三比克"},
//	"512": map[string]string{"en": "Oman", "zh_cn": "阿曼", "zh_tw": "阿曼"},
//	"516": map[string]string{"en": "Namibia", "zh_cn": "纳米比亚", "zh_tw": "納米比亞"},
//	"520": map[string]string{"en": "Nauru", "zh_cn": "瑙鲁", "zh_tw": "諾魯"},
//	"524": map[string]string{"en": "Nepal", "zh_cn": "尼泊尔", "zh_tw": "尼泊爾"},
//	"528": map[string]string{"en": "Netherlands", "zh_cn": "荷兰", "zh_tw": "荷蘭"},
//	"531": map[string]string{"en": "Curaçao", "zh_cn": "库拉索", "zh_tw": "庫拉索"},
//	"533": map[string]string{"en": "Aruba", "zh_cn": "阿鲁巴", "zh_tw": "阿魯巴"},
//	"534": map[string]string{"en": "Sint Maarten (Dutch part)", "zh_cn": "荷属圣马丁", "zh_tw": "荷屬聖馬丁"},
//	"535": map[string]string{"en": "Bonaire, Sint Eustatius and Saba", "zh_cn": "加勒比荷兰", "zh_tw": "加勒比荷蘭"},
//	"540": map[string]string{"en": "New Caledonia", "zh_cn": "新喀里多尼亚", "zh_tw": "新喀里多尼亞"},
//	"548": map[string]string{"en": "Vanuatu", "zh_cn": "瓦努阿图", "zh_tw": "萬那杜"},
//	"554": map[string]string{"en": "New Zealand", "zh_cn": "新西兰", "zh_tw": "紐西蘭"},
//	"558": map[string]string{"en": "Nicaragua", "zh_cn": "尼加拉瓜", "zh_tw": "尼加拉瓜"},
//	"562": map[string]string{"en": "Niger", "zh_cn": "尼日尔", "zh_tw": "尼日"},
//	"566": map[string]string{"en": "Nigeria", "zh_cn": "尼日利亚", "zh_tw": "奈及利亞"},
//	"570": map[string]string{"en": "Niue", "zh_cn": "纽埃", "zh_tw": "紐埃"},
//	"574": map[string]string{"en": "Norfolk Island", "zh_cn": "诺福克岛", "zh_tw": "諾福克島"},
//	"578": map[string]string{"en": "Norway", "zh_cn": "挪威", "zh_tw": "挪威"},
//	"580": map[string]string{"en": "Northern Mariana Islands", "zh_cn": "北马里亚纳群岛", "zh_tw": "北馬裡亞納群島"},
//	"581": map[string]string{"en": "United States Minor Outlying Islands", "zh_cn": "美国本土外小岛屿", "zh_tw": "美國本土外小島嶼"},
//	"583": map[string]string{"en": "Micronesia, Federated States of", "zh_cn": "密克罗尼西亚联邦", "zh_tw": "密克羅尼西亞聯邦"},
//	"584": map[string]string{"en": "Marshall Islands", "zh_cn": "马绍尔群岛", "zh_tw": "馬紹爾群島"},
//	"585": map[string]string{"en": "Palau", "zh_cn": "帕劳", "zh_tw": "帛琉"},
//	"586": map[string]string{"en": "Pakistan", "zh_cn": "巴基斯坦", "zh_tw": "巴基斯坦"},
//	"591": map[string]string{"en": "Panama", "zh_cn": "巴拿马", "zh_tw": "巴拿馬"},
//	"598": map[string]string{"en": "Papua New Guinea", "zh_cn": "巴布亚新几内亚", "zh_tw": "巴布亞紐幾內亞"},
//	"600": map[string]string{"en": "Paraguay", "zh_cn": "巴拉圭", "zh_tw": "巴拉圭"},
//	"604": map[string]string{"en": "Peru", "zh_cn": "秘鲁", "zh_tw": "祕魯"},
//	"608": map[string]string{"en": "Philippines", "zh_cn": "菲律宾", "zh_tw": "菲律賓"},
//	"612": map[string]string{"en": "Pitcairn", "zh_cn": "皮特凯恩群岛", "zh_tw": "皮特凱恩群島"},
//	"616": map[string]string{"en": "Poland", "zh_cn": "波兰", "zh_tw": "波蘭"},
//	"620": map[string]string{"en": "Portugal", "zh_cn": "葡萄牙", "zh_tw": "葡萄牙"},
//	"624": map[string]string{"en": "Guinea-Bissau", "zh_cn": "几内亚比绍", "zh_tw": "幾內亞比索"},
//	"626": map[string]string{"en": "Timor-Leste", "zh_cn": "东帝汶", "zh_tw": "東帝汶"},
//	"630": map[string]string{"en": "Puerto Rico", "zh_cn": "波多黎各", "zh_tw": "波多黎各"},
//	"634": map[string]string{"en": "Qatar", "zh_cn": "卡塔尔", "zh_tw": "卡達"},
//	"638": map[string]string{"en": "Réunion", "zh_cn": "留尼汪", "zh_tw": "留尼汪"},
//	"642": map[string]string{"en": "Romania", "zh_cn": "罗马尼亚", "zh_tw": "羅馬尼亞"},
//	"643": map[string]string{"en": "Russian Federation", "zh_cn": "俄罗斯", "zh_tw": "俄羅斯"},
//	"646": map[string]string{"en": "Rwanda", "zh_cn": "卢旺达", "zh_tw": "盧安達"},
//	"652": map[string]string{"en": "Saint Barthélemy", "zh_cn": "圣巴泰勒米", "zh_tw": "聖巴泰勒米"},
//	"654": map[string]string{"en": "Saint Helena, Ascension and Tristan da Cunha", "zh_cn": "圣赫勒拿", "zh_tw": "聖赫勒拿"},
//	"659": map[string]string{"en": "Saint Kitts and Nevis", "zh_cn": "圣基茨和尼维斯", "zh_tw": "聖克里斯多福及尼維斯"},
//	"660": map[string]string{"en": "Anguilla", "zh_cn": "安圭拉", "zh_tw": "安圭拉"},
//	"662": map[string]string{"en": "Saint Lucia", "zh_cn": "圣卢西亚", "zh_tw": "聖露西亞"},
//	"663": map[string]string{"en": "Saint Martin (French part)", "zh_cn": "法属圣马丁", "zh_tw": "法屬聖馬丁"},
//	"666": map[string]string{"en": "Saint Pierre and Miquelon", "zh_cn": "圣皮埃尔和密克隆", "zh_tw": "聖皮埃爾和密克隆"},
//	"670": map[string]string{"en": "Saint Vincent and the Grenadines", "zh_cn": "圣文森特和格林纳丁斯", "zh_tw": "聖文森及格瑞那丁"},
//	"674": map[string]string{"en": "San Marino", "zh_cn": "圣马力诺", "zh_tw": "聖馬利諾"},
//	"678": map[string]string{"en": "Sao Tome and Principe", "zh_cn": "圣多美和普林西比", "zh_tw": "聖多美和普林西比"},
//	"682": map[string]string{"en": "Saudi Arabia", "zh_cn": "沙特阿拉伯", "zh_tw": "沙烏地阿拉伯"},
//	"686": map[string]string{"en": "Senegal", "zh_cn": "塞内加尔", "zh_tw": "塞內加爾"},
//	"688": map[string]string{"en": "Serbia", "zh_cn": "塞尔维亚", "zh_tw": "塞爾維亞"},
//	"690": map[string]string{"en": "Seychelles", "zh_cn": "塞舌尔", "zh_tw": "塞席爾"},
//	"694": map[string]string{"en": "Sierra Leone", "zh_cn": "塞拉利昂", "zh_tw": "獅子山"},
//	"702": map[string]string{"en": "Singapore", "zh_cn": "新加坡", "zh_tw": "新加坡"},
//	"703": map[string]string{"en": "Slovakia", "zh_cn": "斯洛伐克", "zh_tw": "斯洛伐克"},
//	"704": map[string]string{"en": "Viet Nam", "zh_cn": "越南", "zh_tw": "越南"},
//	"705": map[string]string{"en": "Slovenia", "zh_cn": "斯洛文尼亚", "zh_tw": "斯洛維尼亞"},
//	"706": map[string]string{"en": "Somalia", "zh_cn": "索马里", "zh_tw": "索馬利亞"},
//	"710": map[string]string{"en": "South Africa", "zh_cn": "南非", "zh_tw": "南非"},
//	"716": map[string]string{"en": "Zimbabwe", "zh_cn": "津巴布韦", "zh_tw": "辛巴威"},
//	"724": map[string]string{"en": "Spain", "zh_cn": "西班牙", "zh_tw": "西班牙"},
//	"728": map[string]string{"en": "South Sudan", "zh_cn": "南苏丹", "zh_tw": "南蘇丹"},
//	"729": map[string]string{"en": "Sudan", "zh_cn": "苏丹", "zh_tw": "蘇丹"},
//	"732": map[string]string{"en": "Western Sahara", "zh_cn": "阿拉伯撒哈拉民主共和国", "zh_tw": "阿拉伯撒哈拉民主共和國"},
//	"740": map[string]string{"en": "Suriname", "zh_cn": "苏里南", "zh_tw": "蘇利南"},
//	"744": map[string]string{"en": "Svalbard and Jan Mayen", "zh_cn": "挪威 斯瓦尔巴群岛和扬马延岛", "zh_tw": "挪威 斯瓦爾巴群島和揚馬延島"},
//	"748": map[string]string{"en": "Swaziland", "zh_cn": "斯威士兰", "zh_tw": "史瓦濟蘭"},
//	"752": map[string]string{"en": "Sweden", "zh_cn": "瑞典", "zh_tw": "瑞典"},
//	"756": map[string]string{"en": "Switzerland", "zh_cn": "瑞士", "zh_tw": "瑞士"},
//	"760": map[string]string{"en": "Syrian Arab Republic", "zh_cn": "叙利亚", "zh_tw": "敘利亞"},
//	"762": map[string]string{"en": "Tajikistan", "zh_cn": "塔吉克斯坦", "zh_tw": "塔吉克"},
//	"764": map[string]string{"en": "Thailand", "zh_cn": "泰国", "zh_tw": "泰國"},
//	"768": map[string]string{"en": "Togo", "zh_cn": "多哥", "zh_tw": "多哥"},
//	"772": map[string]string{"en": "Tokelau", "zh_cn": "托克劳", "zh_tw": "托克勞"},
//	"776": map[string]string{"en": "Tonga", "zh_cn": "汤加", "zh_tw": "湯加"},
//	"780": map[string]string{"en": "Trinidad and Tobago", "zh_cn": "特立尼达和多巴哥", "zh_tw": "千里達及托巴哥"},
//	"784": map[string]string{"en": "United Arab Emirates", "zh_cn": "阿联酋", "zh_tw": "阿聯酋"},
//	"788": map[string]string{"en": "Tunisia", "zh_cn": "突尼斯", "zh_tw": "突尼西亞"},
//	"792": map[string]string{"en": "Turkey", "zh_cn": "土耳其", "zh_tw": "土耳其"},
//	"795": map[string]string{"en": "Turkmenistan", "zh_cn": "土库曼斯坦", "zh_tw": "土庫曼"},
//	"796": map[string]string{"en": "Turks and Caicos Islands", "zh_cn": "特克斯和凯科斯群岛", "zh_tw": "特克斯和凱科斯群島"},
//	"798": map[string]string{"en": "Tuvalu", "zh_cn": "图瓦卢", "zh_tw": "吐瓦魯"},
//	"800": map[string]string{"en": "Uganda", "zh_cn": "乌干达", "zh_tw": "烏干達"},
//	"804": map[string]string{"en": "Ukraine", "zh_cn": "乌克兰", "zh_tw": "烏克蘭"},
//	"807": map[string]string{"en": "Macedonia, the former Yugoslav Republic of", "zh_cn": "马其顿", "zh_tw": "馬其頓"},
//	"818": map[string]string{"en": "Egypt", "zh_cn": "埃及", "zh_tw": "埃及"},
//	"826": map[string]string{"en": "United Kingdom", "zh_cn": "英国", "zh_tw": "英國"},
//	"831": map[string]string{"en": "Guernsey", "zh_cn": "根西", "zh_tw": "根西"},
//	"832": map[string]string{"en": "Jersey", "zh_cn": "泽西", "zh_tw": "澤西"},
//	"833": map[string]string{"en": "Isle of Man", "zh_cn": "马恩岛", "zh_tw": "馬恩島"},
//	"834": map[string]string{"en": "Tanzania, United Republic of", "zh_cn": "坦桑尼亚", "zh_tw": "坦尚尼亞"},
//	"840": map[string]string{"en": "United States of America", "zh_cn": "美国", "zh_tw": "美國"},
//	"850": map[string]string{"en": "Virgin Islands, U.S.", "zh_cn": "美属维尔京群岛", "zh_tw": "美屬維爾京群島"},
//	"854": map[string]string{"en": "Burkina Faso", "zh_cn": "布基纳法索", "zh_tw": "布吉納法索"},
//	"858": map[string]string{"en": "Uruguay", "zh_cn": "乌拉圭", "zh_tw": "烏拉圭"},
//	"860": map[string]string{"en": "Uzbekistan", "zh_cn": "乌兹别克斯坦", "zh_tw": "烏茲別克"},
//	"862": map[string]string{"en": "Venezuela, Bolivarian Republic of", "zh_cn": "委内瑞拉", "zh_tw": "委內瑞拉"},
//	"876": map[string]string{"en": "Wallis and Futuna", "zh_cn": "瓦利斯和富图纳", "zh_tw": "瓦利斯和富圖納"},
//	"882": map[string]string{"en": "Samoa", "zh_cn": "萨摩亚", "zh_tw": "薩摩亞"},
//	"887": map[string]string{"en": "Yemen", "zh_cn": "也门", "zh_tw": "葉門"},
//	"894": map[string]string{"en": "Zambia", "zh_cn": "赞比亚", "zh_tw": "尚比亞"},
//	"530": map[string]string{"en": "Netherlands Antilles", "zh_cn": "荷属安的列斯群岛", "zh_tw": "荷屬安的列斯群島"},
//	"736": map[string]string{"en": "Sudan", "zh_cn": "苏丹", "zh_tw": "蘇丹"},
//	"998": map[string]string{"en": "Kosovo", "zh_cn": "科索沃", "zh_tw": "科索沃"},
//	"999": map[string]string{"en": "Other countries or regions", "zh_cn": "其他国家或地区", "zh_tw": "其他國家或地區"},
//	"000": map[string]string{"en": "Other countries or regions", "zh_cn": "其他国家或地区", "zh_tw": "其他國家或地區"},
//}

func Get(k string) map[string]string {

	var res = map[string]string{}

	pattern := "\\d+"
	isNum, _ := regexp.MatchString(pattern, k)
	if isNum {
		if r, ok := codes[k]; ok {
			return r
		}
	} else {
		if num, ok := names[k]; ok {
			if r, ok2 := codes[num]; ok2 {
				return r
			}
		}
	}

	return res
}
