server:
  run-mode: release
  http-port: 8080
  read-timeout: 60
  write-timeout: 60
  ipdb-path: /app/ipdb

logrus-config: &logrusConfig
  code: logrus
  level: info
  format: json
  enable-caller: true
  file-name: /tmp/adms-go/adms.log
  enable-kafka: true

zookeeper: 10.10.182.158:2181,10.10.101.151:2181,10.10.102.25:2181

log-config: *logrusConfig

